name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ushastii.beget.tech }}
        username: ${{ secrets.ushastii_totoservis }}
        key: ${{ secrets.&n7WBPq4 }}
        script: |
          cd /path/to/your/project
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
